version: '3.8'

services:
  db:
    image: mysql:9.0
    container_name: mysql_nest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nestjs:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      # - DB_HOST=autorack.proxy.rlwy.net
      # - DB_PORT=15034
      # - DB_USERNAME=root
      # - DB_PASSWORD=TTiVqSzqcBTzhBKoBkBDwlNIFojgTOnh
      # - DB_DATABASE=railway
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - DB_DATABASE=mydatabase
    command: sh -c "npm run migration:run && npm run build && npm run start:prod"

volumes:
  mysql_data:
